apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels:
    app: frontend
spec: 
  containers:
    - name: webserver
      image: nginx
      ports: 
        - name: webserver
          containerPort: 80
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata: 
  name: my-service
spec: 
  selector:
   #- name: apache
   app: frontend
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30010