apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-replic
  labels:
    app: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      school: pl 
  template:
    metadata:
      labels:
        school: pl 
    spec:
      containers:
      - name: apache
        image: httpd
        ports:
          - containerPort: 80
          


---
apiVersion: v1
kind: Service
metadata:
  name: replica-service
spec:
  selector:
    school: pl
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30020

