apiVersion: v1
kind: Pod
metadata: 
  name: apache
spec: 
  containers:
    - name: apache
      image: httpd:latest
      ports: 
        - name: apache
          containerPort: 80
          protocol: TCP

---
# apiVersion: apps/v1beta2
# kind: Deployment
# metadata: 
# name: apache-deployment